---
title: Використовуй шрифти зі стартового проєкту
hero_image: images/banner.png
description: Використовуй шрифти зі стартового проєкту.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Використовуй шрифти зі стартового проєкту
