title: Utiliser les polices du projet de démarrage
hero_image: images/banner.png
description: Use fonts from the starter project.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Utiliser les polices du projet de démarrage
