title: Use fonts from the starter project
hero_image: images/banner.png
description: Use fonts from the starter project
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Use fonts from the starter project
